// Wails runtime type declarations.
// In a real Wails project this is auto-generated by `wails dev`.

/** Subscribe to an event. Returns an unsubscribe function. */
export function on(event: string, callback: (...args: any[]) => void): () => void;

/** Unsubscribe from an event. */
export function off(event: string, callback: (...args: any[]) => void): void;

/** Emit an event (JS → Go). */
export function emit(event: string, ...args: any[]): void;

/** Call a Go app method. */
export function appCall(method: string, ...args: any[]): Promise<any>;

/** The Events namespace (alternative to importing functions directly). */
export const Events: {
    on: typeof on;
    off: typeof off;
    emit: typeof emit;
};

/** Window control methods. */
export const Window: {
    Minimise(): void;
    Maximise(): void;
    Unmaximise(): void;
    Fullscreen(): void;
    Unfullscreen(): void;
    Close(): void;
};

/** Log levels and methods. */
export const Log: {
    log: (msg: string) => void;
    info: (msg: string) => void;
    warn: (msg: string) => void;
    error: (msg: string) => void;
    debug: (msg: string) => void;
};
