// Auto-generated Wails bindings for the App struct.
// In a real Wails project this file is generated by `wails dev`.
// Do not edit manually.
import type { Host } from '../../../src/types';

export class App {
    static GetHosts(): Promise<Array<Host>>;
    static SaveHost(h: Host): Promise<void>;
    static DeleteHost(id: string): Promise<void>;
    static OpenTab(hostID: string, cols: number, rows: number): Promise<string>;
    static Write(sid: string, data: string): Promise<void>;
    static Resize(sid: string, cols: number, rows: number): Promise<void>;
    static CloseTab(sid: string): Promise<void>;
    static UnlockDB(passphrase: string): Promise<void>;
    static SetupDB(passphrase: string): Promise<void>;
    static GetSettings(): Promise<Record<string, string>>;
    static SetSetting(key: string, value: string): Promise<void>;
}
